---
# Reproducer for: "Failed to JSON parse a line from worker stream"
#
# PREREQ: Pre-fill disk on exec node leaving ~200MB:
#   sudo dd if=/dev/zero of=/tmp/fill-disk bs=1M count=9500
#
# The receptor stdout file is in /var/lib/receptor/<work-unit-id>/stdout
# We need to fill that filesystem while the job is streaming output.

- name: Reproduce JSON parse error from disk full
  hosts: all
  gather_facts: false
  tasks:
    - name: Fill receptor work directory in background
      shell: |
        nohup bash -c '
          sleep 1
          # Fill /var/lib/receptor specifically
          while true; do
            dd if=/dev/zero of=/var/lib/receptor/fill-$RANDOM bs=1M count=10 2>/dev/null || break
          done
          # Also fill /tmp as backup
          while true; do
            dd if=/dev/zero of=/tmp/fill-$RANDOM bs=1M count=10 2>/dev/null || break
          done
        ' >/dev/null 2>&1 &
      async: 1
      poll: 0

    - name: Sleep to let disk filler start
      pause:
        seconds: 2

    - name: Generate continuous large output to grow stdout file
      shell: |
        echo "{{ item }}: $(python3 -c "print('X' * 1000)") - Padding to grow receptor stdout file"
      loop: "{{ range(1, 5000) | list }}"
      ignore_errors: true

    - name: More output after potential disk full
      debug:
        msg: "Post-fill output {{ item }}: This line may fail to write if disk is full"
      loop: "{{ range(1, 1000) | list }}"
      ignore_errors: true
