---
- name: Reproduce JSON parse error from disk full
  hosts: all
  gather_facts: false
  tasks:
    - name: Start generating output
      debug:
        msg: "Starting job - disk has space"

    - name: Fill the disk during job execution
      shell: |
        # Fill remaining disk space minus a tiny buffer
        AVAIL=$(df --output=avail / | tail -1)
        FILL_SIZE=$((AVAIL - 1024))  # Leave 1MB
        if [ $FILL_SIZE -gt 0 ]; then
          dd if=/dev/zero of=/tmp/fill-disk-job bs=1K count=$FILL_SIZE 2>/dev/null || true
        fi

    - name: Generate lots of output to trigger JSON write
      debug:
        msg: "{{ item }}: This is output line that needs to be written to JSON. Generating lots of text to increase the chance of JSON truncation when disk is full."
      loop: "{{ range(1, 500) | list }}"

    - name: More tasks to extend JSON output
      shell: echo "Task {{ item }} output for JSON"
      loop: "{{ range(1, 100) | list }}"
      register: shell_output

    - name: Debug large registered variable
      debug:
        var: shell_output
