---
# Reproducer for: "Failed to JSON parse a line from worker stream"
#
# PREREQ: Pre-fill disk on exec node leaving only ~50MB:
#   sudo rm -f /tmp/fill-* /var/lib/receptor/fill-*
#   sudo dd if=/dev/zero of=/tmp/fill-disk bs=1M count=9800
#   df -h /
#
# Then run this job - the output will exceed 50MB and cause JSON truncation

- name: Reproduce JSON parse error from disk full
  hosts: all
  gather_facts: false
  tasks:
    - name: Generate massive output to exceed remaining disk space
      shell: |
        python3 -c "print('OUTPUT_LINE_{{ item }}: ' + 'X' * 2000)"
      loop: "{{ range(1, 10000) | list }}"

    - name: Even more output
      debug:
        msg: "DEBUG_{{ item }}: {{ 'Y' * 1000 }}"
      loop: "{{ range(1, 5000) | list }}"
