---
# Reproducer for: "Failed to JSON parse a line from worker stream"
#
# This playbook uses a role with large files in files/ directory.
# The copy tasks trigger transmission of these files via receptor.
# When the execution node disk is nearly full, the transmission
# will fail mid-write causing truncated JSON in the stdout file.
#
# IMPORTANT: The data files must be created on the control node.
# See README.md for setup instructions.

- name: Large files test for JSON parse error
  hosts: all
  gather_facts: false
  roles:
    - largefiles
