---
# PREREQ: Pre-fill the disk on exec node first!
# Run: dd if=/dev/zero of=/tmp/fill-disk bs=1M count=9000
# This leaves ~500MB free

- name: Reproduce JSON parse error from disk full
  hosts: all
  gather_facts: false
  tasks:
    - name: Start background disk filler
      shell: |
        nohup bash -c 'sleep 2; while true; do dd if=/dev/zero of=/tmp/fill-bg-$RANDOM bs=1M count=50 2>/dev/null || break; done' &
      async: 1
      poll: 0

    - name: Generate massive output to fill remaining space and cause JSON truncation
      debug:
        msg: "{{ item }}: {{ 'X' * 500 }} - Large output line to consume disk space during JSON streaming"
      loop: "{{ range(1, 2000) | list }}"

    - name: More output with shell commands
      shell: |
        for i in $(seq 1 50); do
          echo "Line $i from shell {{ item }}: $(date) - extra padding text to increase output size"
        done
      loop: "{{ range(1, 100) | list }}"
      register: massive_output

    - name: Dump registered variable
      debug:
        var: massive_output
