---
# Reproducer for: "Failed to JSON parse a line from worker stream"
#
# This playbook uses large collections to increase the project size transmitted
# via receptor. When the execution node disk is nearly full, the transmission
# will fail mid-write causing truncated JSON in the stdout file.
#
# See README.md for reproduction steps.

- name: Large collection test for JSON parse error
  hosts: all
  gather_facts: false
  collections:
    - azure.azcollection
    - amazon.aws
    - google.cloud
    - cisco.aci
    - vmware.vmware_rest
    - kubernetes.core
    - community.vmware
    - community.aws
  tasks:
    - name: Show disk usage before test
      ansible.builtin.shell: df -h /tmp /var/lib/receptor 2>/dev/null || df -h /tmp
      register: disk_before

    - name: Display disk usage
      ansible.builtin.debug:
        var: disk_before.stdout_lines

    - name: Simple task to verify execution
      ansible.builtin.debug:
        msg: "Large collection test completed - collections transmitted successfully"
