---
- name: CPU Exhaustion Test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Consume CPU cycles (gentle, respects resource limits)
      shell: |
        python3 << 'PYEOF'
        import time

        print("Starting gentle CPU burn...")
        start_time = time.time()
        count = 0

        # Run for 60 seconds with a single thread
        while time.time() - start_time < 60:
            count += 1
            # CPU-intensive calculation
            _ = sum(i*i for i in range(10000))

            # Brief sleep every 1000 iterations to be gentle
            if count % 1000 == 0:
                elapsed = time.time() - start_time
                print(f"Progress: {elapsed:.1f}s - {count} iterations")
                time.sleep(0.01)  # 10ms pause

        total_time = time.time() - start_time
        print(f"Completed: {count} iterations in {total_time:.2f}s")
        print("CPU test finished successfully")
        PYEOF
      register: result

    - name: Show result
      debug:
        var: result.stdout_lines
