---
collections:
  # Large collections to increase project transmission size
  # azure.azcollection is ~50MB, amazon.aws is ~30MB
  - name: azure.azcollection
    version: ">=2.0.0"
  - name: amazon.aws
    version: ">=7.0.0"
  - name: google.cloud
    version: ">=1.3.0"
  - name: cisco.aci
    version: ">=2.0.0"
  - name: vmware.vmware_rest
    version: ">=3.0.0"
  - name: kubernetes.core
    version: ">=3.0.0"
  - name: community.vmware
    version: ">=4.0.0"
  - name: community.aws
    version: ">=7.0.0"
