---
- name: Show facts on a host
  hosts: all
  tasks:
    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out

    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Show the output of setup
      ansible.builtin.setup:
      register: setup_out

    - ansible.builtin.debug:
        var: setup_out

    - name: Show info_out
      ansible.builtin.debug:
        var: info_out
